name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Snapcraft is optional - uncomment if you want to publish to Snap Store
      # - name: Install Snapcraft (Linux only)
      #   uses: samuelmeuli/action-snapcraft@v2
      #   if: startsWith(matrix.os, 'ubuntu')

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Automatically release when a tag is pushed
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          
          # macOS code signing (optional, for later)
          # mac_certs: ${{ secrets.MAC_CERTS }}
          # mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}
          
          # Windows code signing (optional, for later)
          # windows_certs: ${{ secrets.WINDOWS_CERTS }}
          # windows_certs_password: ${{ secrets.WINDOWS_CERTS_PASSWORD }}